@base_url=http://localhost:8080/api/v1

### List Openings

GET {{base_url}}/openings
Accept: application/json
Content-Type: application/json

### Get Opening

@opening_id=2

GET {{base_url}}/opening?id={{opening_id}}
Content-Type: application/json

### Create Opening

POST {{base_url}}/opening
Content-Type: application/json

{
    "role": "Senior da Vida",
    "company": "Life God",
    "location": "Somewhere",
    "remote": false,
    "link": "http://localhost:2000",
    "salary": 520000
}

### Update Opening

@opening_id=2

PUT {{base_url}}/opening?id={{opening_id}}
Content-Type: application/json

{ 
    "company": "Gaagle"
}

### Delete Opening

DELETE {{base_url}}/opening?id=1
Content-Type: application/json
